---
# If you cloned this repo from GitHub, don't change this file! If you update with a git pull, it's likely there will be
# changes that will need to be merged. If you're comfortable with this, that's fine, but ideally you should copy this
# and put your own data in that one. If you're missing data in your user-created config, Repost Bot will fall back on
# this file.

repost_data_path: "group_settings/"  # the folder where all group repost data will be stored.

bot_admin_id: 123                    # your personal user id, used to override group admin settings to reset group repost data.
                                     # use the /userid command in a private chat with the bot to echo your telegram user id.

bot_token: "your token here"         # get this from BotFather.

hash_size: 22                        # lower numbers = smaller file sizes, but less precise hashes and more false positives.
                                     # try not to go below 20; higher than 24 may result in false negatives.

flood_protection_timeout: 2          # time in seconds that must pass before repost bot will make another callout in a group.
                                     # (this also affects how often the bot will respond to each person in each group)

callout_style: "singular"            # "verbose" or "singular". determines if bot calls out each repost individually or
                                     # addresses it with a single response. warning: "verbose" can be very spammy, but it
                                     # is pretty funny.

default_toggles:                     # repost bot can be configured by default to track URLs and pictures.
  url: true                          # users can use the /toggle command to change these at any time.
  picture: true
  autocallout: true                  # toggles whether Repost Bot automatically calls out reposts.
  autodelete: false                  # toggles whether Repost Bot automatically deletes reposts.

group_whitelist: []                  # use these to allow or disallow specific groups from using the bot.
group_blacklist: []                  # these cannot both have values. only one or none of these should be used.

# these are the strings used for the bot's various responses, and also for its repost callout strategies.
# if you create a new strategy, the strings for its responses need to be in here and the keys to refer to it
# need to be returned in its get_required_strings() method
strings:
  private_chat: "I don't care about reposts just between us. I only check in group chats. Add me to a group."
  private_chat_toggle: "I don't track reposts in private chats."

  help_command: "I'm {name}. I analyze the pictures and URLs you send and call people out when they send something that's been sent before.
   \nI store the message ID, hashed versions of the URLs and pictures you send, the user ID of the sender and the ID of the group it was sent in. GIFs and videos are not tracked.
   \n\n/toggle [url | picture | autocallout | autodelete] - Toggle various settings for Repost Bot. Untoggling tracking of URLs and pictures means they will not be logged or acknowledged. Multiple options can be toggled at a time.
   \n/settings - Display Repost Bot settings for this group.
   \n/whitelist - Use this command while replying to the message containing a specific URL or picture you want to whitelist. Whitelisted items will still be logged, but I won't call reposts of it out.
   \n/reset - Only group admins and the bot admin can call this command. Deletes all repost and whitelist data, resets toggles to default settings. This can't be undone.
   \n/stats - Display number of unique images and URLs I have seen, and how many reposts of each. Note that the first time it is seen is not counted as a repost.
   \n\nFlood protection is on a per-user-per-command basis, including calling out reposts. I will still track posts when being flooded, but will not call them out."

  settings_command_response: "RepostBot toggleable settings:"
  enabled: "Enabled"
  disabled: "Disabled"

  settings_track_pictures: "Track Pictures"
  settings_track_urls: "Track URLs"
  settings_auto_callout: "Auto Callout"
  settings_auto_delete: "Auto Delete"

  invalid_whitelist_reply: "Use /whitelist while replying to a message so I can whitelist what's in it."
  removed_from_whitelist_reply: "I'll start tracking reposts of that again."
  successful_whitelist_reply: "I won't track reposts of that from now on."
  added_and_removed_from_whitelist_reply: "In that message, there were entities that were both whitelisted and not. I'll track reposts of the ones that I wasn't before, and stop tracking ones that I was."

  group_repost_reset_initial_prompt: "Are you sure you want to delete the group's repost data? This is irreversible."
  group_reset_yes: "Yes"
  group_reset_no: "No"
  group_reset_confirmation_responses: [
    "y",
    "ye",
    "yes",
    "yea",
    "yeah",
    "yep",
    "yeppers",
    "affirmative",
    "mhm",
    "mhmm",
    "indeed",
    "yas",
    "si",
    "yis",
    "do it",
    "go ahead",
    "proceed",
    "go",
    "go on",
  ]
  group_repost_reset_admin_only: "Only admins can do this action."
  group_repost_reset_cancel: "I won't delete it then."
  group_repost_data_reset: "The group repost data has been reset."

  stats_command_reply: "Unique pictures posted: {num_unique_images:n}
  \nTotal image reposts: {num_image_reposts:n}
  \nUnique URLs posted: {num_unique_urls:n}
  \nTotal URL reposts: {num_url_reposts:n}"

  # these three strings are for the verbose callout response style
  repost_alert: "My friend, you've posted unoriginal content!"
  first_repost_callout: "Look, it was here first."
  final_repost_callout: "Let's keep the reposting to a minimum mmkay, {name}?"

  # one of these will be chosen at random for each message in a repost set, also part of the verbose style
  intermediary_callouts: [
      "And here as well!",
      "Here it is again!",
      "Another one right here",
  ]

  # these next two string sets are for the single message callout style (singular)
  single_callout_one_repost_options: [
      "Attention {name}: this is a repost. Everyone look and laugh at them."
  ]

  single_callout_x_num_reposts_options: [
      "{name}, you know this has been posted {num} times before, right? Crazy."
  ]

  # what the bot should say when blacklisted groups attempt to use it
  blacklisted_response: "This group has been banned from using this bot."

  # what the bot should say when non-whitelisted groups attempt to use it
  not_in_whitelist_response: "This group is not allowed to use this bot."